### PR TITLE
Added file locking for thread-safe SQL operations.

### PR DESCRIPTION
**Pull request by LTLA**
Exactly what it says on the tin. Consider the following code:

```r
library(BiocFileCache)

unlink("here", recursive=TRUE) # clearing it out.
bfc <- BiocFileCache("here", ask=FALSE)

library(BiocParallel)
bplapply(1:10, function(x) {
    bfcnew(bfc, paste0("YAY", x))
})
```

With the package as it currently is, we run into a variety of race conditions:

```
Error: BiocParallel errors
  element index: 1, 2, 3, 8
  first error: attempt to write a readonly database
```

Or even:

```
Error: BiocParallel errors
  element index: 2, 6, 8
  first error: disk I/O error
```

With this PR, we get something a bit better. The names are actually unique (varying on the ~4th character), which threw me for a bit of a loop at first. The numbers are scrambled in order but that's okay.

```
[[1]]
                            BFC1 
"here/41da2ca92535_41da2ca92535" 

[[2]]
                            BFC2 
"here/41db2ca92535_41db2ca92535" 

[[3]]
                            BFC6 
"here/41dc2ca92535_41dc2ca92535" 

[[4]]
                            BFC3 
"here/41dd2ca92535_41dd2ca92535" 

[[5]]
                           BFC10 
"here/41de2ca92535_41de2ca92535" 

[[6]]
                            BFC8 
"here/41df2ca92535_41df2ca92535" 

[[7]]
                            BFC5 
"here/41e02ca92535_41e02ca92535" 

[[8]]
                            BFC7 
"here/41e12ca92535_41e12ca92535" 

[[9]]
                            BFC4 
"here/41e22ca92535_41e22ca92535" 

[[10]]
                            BFC9 
"here/41e32ca92535_41e32ca92535" 
```

The changes themselves are minor, just wrapping **filelock** around each (dis)connection to the SQLite backend. I am not sure of the exact relationship between **BiocFileCache** and **ExperimentHub** but I suspect a similar procedure could be implemented in the latter if they do not already share the same caching machinery.

### CODE REVIEW

**Comment by mtmorgan** [comment]
I agree internal locking makes sense. For what it's worth BiocParallel provides `ipc*()` functions for inter-process locks.

```
bplapply(1:10, function(x, id) {
    ipclock(id); on.exit(ipcunlock(id))
    bfcnew(bfc, paste0("YAY", x)) 
}, id = ipcid())
```

**Comment by LTLA** [comment]
I figured that any task touching the file system should also use the file system for locking, given that writes might be coming from, e.g., different nodes on a cluster, possibly even from different users. Shared file locks are also nice for read-only access.

**Comment by lshep** [comment]
Hello @LTLA   
Question:  For the `.sql_disconnect` function,  It seemed like disconnecting from the database before releasing the lock would be the better order.  Is there a reason you unlocked before disconnecting?  

For consistency, we'll rename the `.lock_path` to `.sql_lock_path` and update accordingly.  I can take care of this renaming or you can add to the PR, just let me know.

**Comment by LTLA** [comment]
> Is there a reason you unlocked before disconnecting?

Nope, I probably wasn't thinking too much about it.

> I can take care of this renaming or you can add to the PR, just let me know.

Go ahead, it's all yours.

**Comment by lshep** [comment]
Great I'll make those changes and merge.  Thanks again for the pull request!

**Comment by lshep** [comment]
When I try to build its giving me an ERROR -- trying to debug

**Comment by lshep** [comment]
```
(base) shepherd@jbcj433:~/BioconductorPackages/Software/BiocFileCache(LTLA-master)$ cd ..
(base) shepherd@jbcj433:~/BioconductorPackages/Software$ R CMD build BiocFileCache 
Bioconductor version 3.12 (BiocManager 1.30.10), ?BiocManager::install for help
* checking for file 'BiocFileCache/DESCRIPTION' ... OK
* preparing 'BiocFileCache':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘BiocFileCache.Rmd’ using rmarkdown
Loading required package: dbplyr
Quitting from lines 363-369 (BiocFileCache.Rmd) 
Quitting from lines 363-369 (BiocFileCache.Rmd) 
Error: processing vignette 'BiocFileCache.Rmd' failed with diagnostics:
error in evaluating the argument 'conn' in selecting a method for function 'dbDisconnect': object 'info' not found
--- failed re-building ‘BiocFileCache.Rmd’

SUMMARY: processing the following file failed:
  ‘BiocFileCache.Rmd’

Error: Vignette re-building failed.
Execution halted
```

**Comment by lshep** [comment]
So....  that R chunk is 
```

'''{r}
suppressPackageStartupMessages({
    library(dplyr)
})
bfcinfo(bfc, "BFC6") %>% select(rid, rpath, fpath)
bfcupdate(bfc, "BFC6", fpath=url, rname="Duplicate", ask=FALSE)
bfcinfo(bfc, "BFC6") %>% select(rid, rpath, fpath)
'''
```

When I run it manually: 

```
> suppressPackageStartupMessages({
+     library(dplyr)
+ })
> bfcinfo(bfc, "BFC6") %>% select(rid, rpath, fpath)
# A tibble: 1 x 3
  rid   rpath                                     fpath                         
  <chr> <chr>                                     <chr>                         
1 BFC6  /tmp/Rtmpdh5PLx/file73b028a1325d/73b06ae… https://en.wikipedia.org/wiki…
> bfcupdate(bfc, "BFC6", fpath=url, rname="Duplicate", ask=FALSE)
Error in lock(.sql_lock_path(dbfile), exclusive = FALSE) : 
  File already has an exclusive lock
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'conn' in selecting a method for function 'dbDisconnect': object 'info' not found
```

**Comment by LTLA** [comment]
Looks like the protective clause in `BiocFileCache-class.R`:

```
                if (is.null(info)) {
                    # The connection is not actually necessary - but we just use it to
                    # handle thread-safe locking, specifically to avoid race conditions
                    # from multiple threads choosing the same tempfile name during download.
                    info <- .sql_connect_RW(.sql_dbfile(x))
                    on.exit(.sql_disconnect(info))
                }
```

is incorrect as locking is handled inside `.sql_get_rpath()` inside `util_download_and_rename`. However, locking is still technically _necessary_ here to avoid two workers from choosing the same `tempfile()` names. Suggest moving this block inside `util_download_and_rename` after `.sql_get_rpath()`

**Comment by lshep** [comment]
That got us one chunk farther and now fails when calling bfcdownload in chunk 381 
```
* creating vignettes ... ERROR
--- re-building ‘BiocFileCache.Rmd’ using rmarkdown
Loading required package: dbplyr
Quitting from lines 381-385 (BiocFileCache.Rmd) 
Quitting from lines 381-385 (BiocFileCache.Rmd) 
Error: processing vignette 'BiocFileCache.Rmd' failed with diagnostics:
error in evaluating the argument 'conn' in selecting a method for function 'dbDisconnect': object 'info' not found
--- failed re-building ‘BiocFileCache.Rmd’

```
The next section of code run manually
```
> rid <- "BFC5"
> test <- !identical(bfcneedsupdate(bfc, rid), FALSE) # 'TRUE' or 'NA'
> if (test)
+     bfcdownload(bfc, rid, ask=FALSE)
Error in lock(.sql_lock_path(dbfile), exclusive = FALSE) : 
  File already has an exclusive lock
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'conn' in selecting a method for function 'dbDisconnect': object 'info' not found
```

**Comment by lshep** [comment]
I created a branch on the BiocFileCache github with the same name LTLA-master  that reflects the renaming/reordering and the first suggested code reorg.

**Comment by LTLA** [comment]
You should already be able to push to my fork, I've turned on "Allow edits by maintainers". IIRC this means you can clone my repo and just commit directly to the `master` branch.

**Comment by LTLA** [comment]
As for the problem above; you need to `force` evaluation of the `fpath` promise, which requires DB access. Otherwise it is only evaluated after the function-wide exclusive lock is established, which breaks because a process can only have one lock.

**Comment by lshep** [comment]
I tried adding `force(fpath)` to the start of `.util_download_and_rename`  but it didn't help.  
```
* creating vignettes ... ERROR
--- re-building ‘BiocFileCache.Rmd’ using rmarkdown
Loading required package: dbplyr
Quitting from lines 363-369 (BiocFileCache.Rmd) 
Error: processing vignette 'BiocFileCache.Rmd' failed with diagnostics:
object 'info' not found
```

Is it because the upper level functions in the BiocFileCache-class.R like `bfcupdate` are potentially calling  `.sql_get_rtype` ? 

```
> suppressPackageStartupMessages({
+     library(dplyr)
+ })
> bfcinfo(bfc, "BFC6") %>% select(rid, rpath, fpath)
# A tibble: 1 x 3
  rid   rpath                                     fpath                         
  <chr> <chr>                                     <chr>                         
1 BFC6  /tmp/RtmpuIozkc/file22ee43daadfb/22ee2ed… https://en.wikipedia.org/wiki…
> bfcupdate(bfc, "BFC6", fpath=url, rname="Duplicate", ask=FALSE)
Error in .util_download_and_rename(x, rids[i], proxy, config, "bfcupdate()",  : 
  object 'info' not found
```

**Comment by LTLA** [comment]
The copy-paste was a bit more literal than I intended. This should now be fixed. It almost passes check but there are some `list.files()` tests that need a `+1` to their expected number of files due to the addition of the new LOCK file.

**Comment by lshep** [comment]
I fixed the tests for the extra file in the directory and updated the exportbfc to not include the LOCK file when exporting.  I think everything looks good.  I'm only going to merge into devel for right now.  Lets monitor for a week or two on the builders to make sure this changes doesn't have any catastrophic effects before merging into release.

**Pull request merged**
