### PR TITLE
avoid link 'does not exist' documentation error

### PR DESCRIPTION
**Pull request by mtmorgan**
- makeActiveBinding is not documented in makeActiveBinding.html, so
  \link[base]{makeActiveBinding} is not correct

### CODE REVIEW

**Comment by lshep** [comment]
I'm curious as why the link wouldn't work since you can do `?makeActiveBinding`  -   if we wanted the linke would it be `bindenv` since when you do the help page 
`bindenv                  package:base                  R Documentation`   
I'm worried that the suggested solution will have the warnings on the windows for not specifying package in the link something like   `foo` not found treating as topic or something to the like?

**Comment by mtmorgan** [comment]
From `RShowDoc("R-exts")` section 2.5 it says

> There are two other forms of optional argument specified as \link[pkg]{foo} and \link[pkg:bar]{foo} to link to the package pkg, to files foo.html and bar.html respectively. These are rarely needed...

In the current case the link is `\link[base]{makeActiveBinding}` so the help system looks for documentation derived from a file called `makeActiveBinding.Rd` so one could says `\link[base:bindev]{makeActiveBinding}` to get the exact link. But this seems fragile, because the maintainer of base could decide to rename the file name to something else (ok, unlikely in this case).

Specifying `\link{makeActiveBinding}` means that if there is just a single relevant help page, it will be found. If there are several relevant help pages, the user will be prompted to find the right one. This seems more robust and not inconvenient.

There might be an edge case when the link is to a package that is not available (attached?) when the help page is being compiled, but that isn't relevant here because the base package is always attached.

**Comment by hpages** [comment]
So there is no way to specify a link to an alias defined in a specific package while at the same time being agnostic of the exact file name where the alias is defined? This is unfortunate because this is what we need.

Using `\link{foo}` in package A is not good enough. Here is why:

1. It triggers an `R CMD check` warning if `foo` is documented in a package B that doesn't get loaded when A is loaded (e.g. B is in Suggests or Enhances) . To get rid of the warning I need to specify the package where `foo` is documented. I don't want to know in which file in B `foo` is documented though. Not interested because irrelevant. 
2. If `foo` is documented in packages B and C and if I don't disambiguate the link I'm putting in the man page of my package A, the link that effectively ends up in the HTML version of my man page might be wrong. It's nice that the user will be prompted to find the right one when s/he does `?foo`, but that doesn't solve the problem that the link is wrong.
3. Even if `\link{foo}` is not ambiguous at a given point in time, it might become ambiguous at some point when one of the packages that A depends on (directly or indirectly) adds a new `foo` alias. I 
 have no control on that. This an argument for always embedding the package in the link, no matter what.

So we really need something like `\link[pkg]{foo}` that says "link to `foo` in package `pkg`". Its current meaning that says "link to `foo` in file `foo.html` in package `pkg`" is almost useless.

**Comment by hpages** [comment]
Other than that, the change to `R/makeCachedActiveBinding.R` looks good. I can't speak for the other changes.

**Pull request merged**
