### PR TITLE
Fix argument mismatch of generic to function for bfcupdate

### PR DESCRIPTION
**Pull request by lshep**
https://github.com/Bioconductor/BiocFileCache/issues/44

### CODE REVIEW

**Comment by lshep** [comment]
@LiNk-NY can you test this?

**Comment by LiNk-NY** [comment]
Hi Lori, @lshep 

Thanks for taking a look and updating!

My code currently does this:
```r
bfc <- BiocFileCache()
bquery <- bfcquery(bfc, url, "rname", exact = TRUE)
if (identical(nrow(bquery), 1L) && bfcneedsupdate(bfc, bquery[["rid"]]))
    bfcupdate(x = bfc, rids = bquery[["rid"]], rname = url)
```

With the code in `FixGeneric`, `BiocFileCache` does not re-download the file even though the condition above returns `TRUE`. It seems that the `fpath` argument needs to be provided? 

I get an error when I provide all the arguments: 

```r
bfcupdate(x = bfc, rids = bquery[["rid"]], rname = url, fpath = url, rpath = bfcrpath(bfc, url))
#' Error: bfcupdate() failed
#'   rid: BFC9
#'   reason: resource rtype is not 'web'
```
because the software changed my resource type from `web` to `local`.

Is there a way to track a 'web' resource with a local file and only update when needed?
I'm not sure I have the right commands here...

Best regards,
Marcel

**Comment by lshep** [comment]
Ah--- I know the reason --- bfcupdate is not to update the download resource -- bfcupdate is to update information in the database -- you want bfcdownload if bfcneedsupdate is true

**Comment by lshep** [comment]
bfcupdate(x = bfc, rids = bquery[["rid"]], rname = url)    is basically saying for this rid in the database update the rname to be url --

**Review by LiNk-NY — APPROVED** [review]

**Pull request merged**
